vc14 package - 2019-04-19 - 14.28.29914.0
sous-chefs/vcruntime pull request #40
Opened 2021-04-19 17:32 UTC by derekgroh

# Description

Matches the checksum for vc14 packages as they are updated on a static link, invalidating older configuration.

## Issues Resolved

None, same PR intent as https://github.com/sous-chefs/vcruntime/pull/39

## Check List

- [X] All tests pass. See TESTING.md for details.
- [X] New functionality includes testing.
- [X] New functionality has been documented in the README if applicable.

2021-04-19 17:33 UTC, kitchen-porter commented
<!--
  0 Errors
  1 Warning: This Pull Request is probably ...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-04-19 18:16 UTC, ramereth requested changes

2021-04-19 18:16 UTC, ramereth commented on CHANGELOG.md
> +- update vc14 checksum for '14.28.29914.0' [@derekgroh](https://github.com/derekgroh)
This needs to be moved up to the `# Unreleased` section.

2021-04-19 18:16 UTC, ramereth commented on metadata.rb
> +version           '2.2.1'
Please do not bump this, our automated tooling will do this when we merge it.

2021-04-20 15:50 UTC, derekgroh commented
Not quite sure why the windows-2016 test loaded the old inspec test:

`         * windows_package[Microsoft Visual C++ 2019 Redistributable (x86) - 14.28.29914.0] action install`

``expected that `System Package Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.28.29325` is installed``

Should be good otherwise

2021-04-20 16:07 UTC, ramereth commented
@derekgroh I hope you don't mind but I went ahead and rebased your PR so that the git history was a little cleaner.

2021-04-20 16:18 UTC, ramereth approved these changes

2021-04-20 16:19 UTC, merged

2021-04-20 16:19 UTC, kitchen-porter commented
Released as: [2.2.1](https://github.com/sous-chefs/vcruntime/releases/tag/2.2.1)